// POS-only permissions preset.
// Mirrors the Saleem Collection POS operator (saleemopr@gmail.com) configuration.
// Applied automatically when a Platform Admin creates a user with the "POS" role type.
export const POS_USER_PERMISSIONS_PRESET = {
  menu: {
    pos_sales: true,
    daily_tally: false,
    gst_reports: false,
    recycle_bin: false,
    sale_return: true,
    user_rights: false,
    gst_register: false,
    stock_ageing: false,
    stock_report: false,
    tally_export: false,
    pos_dashboard: false,
    price_history: false,
    product_entry: false,
    purchase_bill: false,
    sale_analysis: false,
    sales_invoice: false,
    settings_view: true,
    whatsapp_logs: true,
    dashboard_view: false,
    main_dashboard: false,
    stock_analysis: false,
    whatsapp_inbox: true,
    customer_ledger: false,
    customer_master: false,
    delivery_update: false,
    einvoice_report: false,
    employee_master: false,
    item_wise_sales: false,
    item_wise_stock: false,
    purchase_return: false,
    quotation_entry: false,
    sales_analytics: false,
    supplier_master: false,
    barcode_printing: false,
    product_tracking: false,
    sale_order_entry: false,
    stock_adjustment: false,
    delivery_whatsapp: false,
    payment_recording: false,
    product_dashboard: false,
    accounts_dashboard: false,
    delivery_dashboard: false,
    payments_dashboard: false,
    purchase_dashboard: false,
    dashboard_customize: false,
    net_profit_analysis: false,
    quotation_dashboard: false,
    daily_cashier_report: false,
    purchase_order_entry: false,
    sale_order_dashboard: false,
    customer_audit_report: false,
    hourly_sales_analysis: false,
    sale_return_dashboard: true,
    sales_report_customer: false,
    accounting_reports_view: false,
    sales_invoice_dashboard: false,
    purchase_order_dashboard: false,
    purchase_report_supplier: false,
    customer_balance_activity: false,
    purchase_return_dashboard: false,
    customer_account_statement: false,
  },
  columns: {
    "purchase_bill.mrp": false,
    "sales_invoice.box": false,
    "sales_invoice.hsn": false,
    "sales_invoice.mrp": false,
  },
  special: {
    ai_chatbot: false,
    audit_logs: false,
    export_data: false,
    whatsapp_send: true,
    cancel_invoice: false,
    delete_records: false,
    modify_records: false,
    detail_accounting: false,
    view_gross_profit: false,
  },
  mainMenu: {
    sales: true,
    master: false,
    reports: false,
    accounts: false,
    delivery: false,
    settings: true,
    dashboard: false,
    inventory: false,
  },
} as const;