import {
  computePurchaseBillTotals,
  computePurchaseLineSubTotal,
} from "@/utils/excelImportUtils";

export type MobilePurchaseLine = {
  temp_id: string;
  product_id: string;
  sku_id: string;
  product_name: string;
  size: string;
  qty: number;
  pur_price: number;
  sale_price: number;
  mrp: number;
  gst_per: number;
  hsn_code: string;
  barcode: string;
  brand: string;
  category: string;
  color: string;
  style: string;
  uom: string;
};

export type MobilePurchaseBillFields = {
  supplierId: string | null;
  supplierName: string;
  supplierInvoiceNo: string;
  billDate: string;
  isDcPurchase: boolean;
  discountAmount: number;
  otherCharges: number;
};

export function prefillPurchasePrice(input: {
  pur_price?: number | string | null;
  last_purchase_pur_price?: number | string | null;
  default_pur_price?: number | string | null;
}): number {
  const a = Number(input.pur_price);
  if (Number.isFinite(a) && a > 0) return a;
  const b = Number(input.last_purchase_pur_price);
  if (Number.isFinite(b) && b > 0) return b;
  const c = Number(input.default_pur_price);
  if (Number.isFinite(c) && c > 0) return c;
  return 0;
}

export function mobilePurchaseLineTotal(
  line: Pick<MobilePurchaseLine, "qty" | "pur_price" | "uom" | "size">,
): number {
  return computePurchaseLineSubTotal(line);
}

/** Surface the RPC's line-numbered errors as-is. */
export function parsePurchaseAtomicSaveError(message: unknown): string {
  const raw = String(message ?? "").trim();
  if (!raw) return "Save failed";
  const lineMatch = raw.match(/Line \d+:[^\n]+/i);
  if (lineMatch) return lineMatch[0].trim();
  const guard = raw.match(/Purchase save guardrail failed:[^\n]+/i);
  if (guard) return guard[0].trim();
  return raw;
}

export function buildMobilePurchaseRpcPayload(
  fields: MobilePurchaseBillFields,
  lines: MobilePurchaseLine[],
  billEntryAt: string = new Date().toISOString(),
): { p_bill: Record<string, unknown>; p_items: Record<string, unknown>[] } {
  const invoice = fields.supplierInvoiceNo.trim();
  const supplierInvAutoGenerated = invoice.length === 0;
  const saveLines = lines.filter((item) => Number(item.qty) > 0);
  const totals = computePurchaseBillTotals(
    saveLines.map((item) => ({
      line_total: mobilePurchaseLineTotal(item),
      gst_per: fields.isDcPurchase ? 0 : Math.round(Number(item.gst_per) || 0),
      qty: Number(item.qty) || 0,
      pur_price: Number(item.pur_price) || 0,
      uom: item.uom,
      size: item.size,
      discount_percent: 0,
    })),
    Number(fields.discountAmount) || 0,
    Number(fields.otherCharges) || 0,
    fields.isDcPurchase,
  );

  const p_items = saveLines.map((item) => ({
    product_id: item.product_id,
    sku_id: item.sku_id,
    product_name: item.product_name,
    size: item.size || "None",
    qty: Number(item.qty) || 0,
    pur_price: Number(item.pur_price) || 0,
    sale_price: Number(item.sale_price) || 0,
    mrp: Number(item.mrp) || 0,
    gst_per: fields.isDcPurchase ? 0 : Math.round(Number(item.gst_per) || 0),
    hsn_code: item.hsn_code || "",
    barcode: item.barcode || "",
    line_total: mobilePurchaseLineTotal(item),
    brand: item.brand || "",
    category: item.category || "",
    color: item.color || "",
    style: item.style || "",
    is_dc_item: fields.isDcPurchase,
  }));

  const p_bill = {
    supplier_id: fields.supplierId || null,
    supplier_name: fields.supplierName.trim(),
    supplier_invoice_no: invoice || null,
    supplier_inv_auto_generated: supplierInvAutoGenerated,
    bill_date: fields.billDate,
    bill_entry_at: billEntryAt,
    gross_amount: totals.grossBeforeDiscount,
    discount_amount: Number(fields.discountAmount) || 0,
    gst_amount: fields.isDcPurchase ? 0 : totals.gstAmount,
    other_charges: Number(fields.otherCharges) || 0,
    net_amount: totals.netAmount,
    round_off: totals.roundOff,
    is_dc_purchase: fields.isDcPurchase,
  };

  return { p_bill, p_items };
}

export function validateMobilePurchaseBeforeSave(
  fields: MobilePurchaseBillFields,
  lines: MobilePurchaseLine[],
): string | null {
  if (!fields.supplierName.trim() && !fields.supplierId) {
    return "Enter a supplier name";
  }
  if (lines.filter((item) => Number(item.qty) > 0).length === 0) {
    return "Add at least one product with quantity greater than 0";
  }
  const badSku = lines.findIndex((item) => Number(item.qty) > 0 && !item.sku_id);
  if (badSku >= 0) return `Line ${badSku + 1}: sku_id is required`;
  const badProduct = lines.findIndex((item) => Number(item.qty) > 0 && !item.product_id);
  if (badProduct >= 0) return `Line ${badProduct + 1}: product_id is required`;
  return null;
}
