-- =============================================================================
-- Repo vs live schema_migrations drift (READ-ONLY pointer)
-- =============================================================================
-- The generated 700-line version list went stale the first time someone added a
-- migration without regenerating it. Use the Node check instead:
--
--   npm run check:schema-drift          -- repo manifest vs files on disk
--   npm run check:schema-drift:write    -- after adding a migration
--   npm run check:schema-drift:live     -- repo vs live (needs credentials)
--
-- See scripts/README-schema-migrations-drift.md
--
-- Manual one-off in the SQL editor (service role):
--   select version from supabase_migrations.schema_migrations order by version;
-- Then diff against: ls supabase/migrations/*.sql
--
-- Critical versions that must be live (also in CRITICAL_SCHEMA_MIGRATIONS):
--   20261001140000  purchase line-qty sold-qty stock floor
--   20260824120000  sale settlement / payment_status normalizer
--   20260628120000  reconcile gross invoiced CN receipts
--   20261126120000  party RPC CN memos via _is_settlement_memo_receipt
